The scaladoc apparently requires Scala 2.12, BIS (#2883)
See: https://github.com/zio/zio-quill/actions/runs/6337872463/job/17215027348#logs

Error:
```scala
[info] Main Scala API documentation to /home/runner/work/zio-quill/zio-quill/zio-quill-docs/target/scala-2.12/unidoc...
java.io.IOException: Scala signature package has wrong version
 expected: 5.0
 found: 5.2 in package.class
```